name: Compile ZeroPilot
on: 
  pull_request: 
    type: [synchronize]

jobs:
    compile:
        name: Compile ZeroPilot
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
            with:
              submodules: 'true'
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: snaccoverflow/build-zp:latest
                options: -v ${{ github.workspace }}:/project
                run: ./Tools/build.bash 