name: Unit Tests
on: 
  pull_request: 
    type: [synchronize]

jobs:
    unit_tests:
        name: Run Unit Tests
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
            with:
              submodules: 'true'
          - name: build and run unit tests with docker
            uses: addnab/docker-run-action@v3
            with:
                image: snaccoverflow/test-zp:latest
                options: -v ${{ github.workspace }}:/project
                run: ./testing/test.bash build && ./testing/test.bash run 